name: Integration test
on:
  pull_request:
  push:
  workflow_call:


jobs:
  # Label of the container job
  integration-test:
    services:
      powerdns:
        image: docker.io/${{ matrix.powerdns_container }}
        env:
          PDNS_AUTH_API_KEY: 1FooBarBaz2!
        ports:
          - "1053:53"
          - "1053:53/udp"
          - "8081:8081"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        powerdns_container: ["powerdns/pdns-auth-49:4.9.3"]
    env:
      POWERDNS_CLI_APIKEY: 1FooBarBaz2!
      POWERDNS_CLI_URL: http://localhost:8081

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10.16
          cache: pip
      - name: Build cli
        run: pip install .
      - name: Add native zone
        run: powerdns-cli add-zone example.org 10.0.0.1 NATIVE
      - name: Add master zone
        run: powerdns-cli add-zone example.com. 10.0.0.1 MASTER
      - name: Add duplicate native zone
        run: powerdns-cli add-zone example.org 10.0.0.1 NATIVE
      - name: Add duplicate master zone
        run: powerdns-cli add-zone example.org 10.0.0.1 MASTER
      - name: Delete zone
        run: powerdns-cli delete-zone -f example.com.
      - name: Delete absent zone
        run: powerdns-cli delete-zone -f example.com
      - name: Add Record
        run: powerdns-cli add-record test example.org A 10.0.0.1
      - name: Add duplicate record
        run: powerdns-cli add-record test example.org A 10.0.0.2
      - name: Add CNAME record with different ttl
        run: powerdns-cli add-record --ttl 60 test1 example.org CNAME "example.org."
      - name: Extend existing record
        run: powerdns-cli extend-record test example.org A 10.0.0.2
      - name: Delete part of a record
        run: powerdns-cli delete-record test example.org A 10.0.0.2
      - name: Delete full record
        run: powerdns-cli delete-record -a test1 example.org CNAME "example.org."
