name: Integration test
on:
  pull_request:
  push:
  workflow_call:


jobs:
  # Label of the container job
  integration-test:
    services:
      powerdns:
        image: docker.io/${{ matrix.powerdns_container }}
        env:
          PDNS_AUTH_API_KEY: 1FooBarBaz2!
        ports:
          - "1053:53"
          - "1053:53/udp"
          - "8081:8081"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        powerdns_container:
          - "powerdns/pdns-auth-49:4.9.3"
          - "powerdns/pdns-auth-48:4.8.4"
          - "powerdns/pdns-auth-47:4.7.4"
    env:
      POWERDNS_CLI_APIKEY: 1FooBarBaz2!
      POWERDNS_CLI_URL: http://localhost:8081

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10.16
          cache: pip
      - name: Build cli
        run: pip install .
# Zone Management Tests
      - name: Add native zone
        run: powerdns-cli add-zone example.org 10.0.0.1 NATIVE
      - name: Add master zone
        run: powerdns-cli add-zone example.com. 10.0.0.1 MASTER
      - name: List zones
        run: powerdns-cli list-zones
      - name: Add duplicate native zone
        run: powerdns-cli add-zone example.org 10.0.0.1 NATIVE
      - name: Add duplicate master zone
        run: powerdns-cli add-zone example.org 10.0.0.1 MASTER
      - name: Delete zone
        run: powerdns-cli delete-zone -f example.com.
      - name: Delete absent zone
        run: powerdns-cli delete-zone -f example.com
      - name: Rectify Zone
        run: powerdns-cli rectify-zone example.org
# Record Management Tests
      - name: Add Record
        run: powerdns-cli add-record add example.org A 10.0.0.1
      - name: Add duplicate record
        run: powerdns-cli add-record add example.org A 10.0.0.2
      - name: Add CNAME record with different ttl
        run: powerdns-cli add-record --ttl 60 cname example.org CNAME "example.org."
      - name: Run extend on no preexisting record
        run: powerdns-cli extend-record extend example.org A 10.0.0.1
      - name: Extend existing record
        run: powerdns-cli extend-record extend example.org A 10.0.0.2
      - name: Create a record to delete
        run: powerdns-cli add-record delete example.org A 10.0.0.1
      - name: Extend a record to delete
        run: powerdns-cli extend-record delete example.org A 10.0.0.2
      - name: Delete part of a record
        run: powerdns-cli delete-record delete example.org A 10.0.0.2
      - name: Delete full record
        run: powerdns-cli delete-record -a delete example.org A 192.168.0.1
      - name: Create a record to disable
        run: powerdns-cli add-record disable example.org A 10.0.0.1
      - name: Disable record
        run: powerdns-cli disable-record disable example.org A 10.0.0.1
# Export Tests
      - name: Export zone as json
        run: powerdns-cli export-zone example.org
      - name: Export zone as bind / afxr
        run: powerdns-cli export-zone -b example.org
# Config Tests
      - name: Show config
        run: powerdns-cli list-config
# Stats Tests
      - name: Show stats
        run: powerdns-cli list-stats
# Search Tests
      - name: Search
        run: powerdns-cli search --max 5 "test.example.org"
# TSIGKey Tests
      - name: Add TSIGKey with defaults
        run: powerdns-cli add-tsigkey test1 hmac-md5
      - name: Add TSIGKey with secrets
        run: powerdns-cli add-tsigkey test2 hmac-sha1 -s "kp4/24gyYsEzbuTVJRUMoqGFmN3LYgVDzJ/3oRSP7ys="
      - name: List TSIGKeys
        run: powerdns-cli list-tsigkeys
      - name: Delete TSIGKeys
        run: powerdns-cli delete-tsigkey test2
      - name: Update TSIGKey secret
        run: powerdns-cli update-tsigkey test1 -s "kp4/24gyYsEzbuTVJRUMoqGFmN3LYgVDzJ/3oRSP7ys="
      - name: Update TSIGKey name
        run: powerdns-cli update-tsigkey test1 -n "newname"
      - name: Update TSIGKey algorithm
        run: powerdns-cli update-tsigkey newname -a "hmac-sha512"
      - name: Export TSIGKey key
        run: powerdns-cli export-tsigkey newname
# Servers Tests
      - name: List servers
        run: powerdns-cli list-servers
      - name: Flush servercache
        run: powerdns-cli flush-cache example.org.
      - name: Export server
        run: powerdns-cli export-server localhost
# Zonemetadata Tests
      - name: Lists zonemetadata
        run: powerdns-cli list-zonemetadata example.org
      - name: Add zonemetadata
        run: powerdns-cli add-zonemetadata example.org ALSO-NOTIFY 192.0.2.1:5305
      - name: Add duplicate zonemetadata
        run: powerdns-cli add-zonemetadata example.org ALSO-NOTIFY 192.0.2.2:5305
      - name: List single zonemetadata value
        run: powerdns-cli list-zonemetadata -l "ALSO-NOTIFY" example.org
      - name: Replace zonemetadata
        run: powerdns-cli replace-zonemetadata example.org ALSO-NOTIFY 192.0.2.2:5305
      - name: Delete zonemetadata
        run: powerdns-cli delete-zonemetadata example.org ALSO-NOTIFY
