name: Integration test
on:
  push:
  workflow_call:


jobs:
  # Label of the container job
  integration-test:
    services:
      powerdns:
        image: ${{ matrix.powerdns_container }}
        env:
          PDNS_AUTH_API_KEY: 1FooBarBaz2!
        ports:
          - "1053:53"
          - "1053:53/udp"
          - "8081:8081"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        powerdns_container:
          - "docker.io/powerdns/pdns-auth-48:4.8.5"
          - "docker.io/powerdns/pdns-auth-49:4.9.5"
          - "docker.io/powerdns/pdns-auth-47:4.7.5"
    env:
      POWERDNS_CLI_APIKEY: 1FooBarBaz2!
      POWERDNS_CLI_URL: http://localhost:8081

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.13.2
          cache: pip
      - name: Build cli
        run: pip install .
# Zone Management Tests
      - name: Add master zone
        run: powerdns-cli zone add example.org MASTER
      - name: Add native zone
        run: powerdns-cli zone add example.com. NATIVE
      - name: List zones
        run: powerdns-cli zone list
      - name: Add duplicate native zone
        run: powerdns-cli zone add example.org NATIVE
      - name: Add duplicate master zone
        run: powerdns-cli zone add example.org MASTER
      - name: Delete zone
        run: powerdns-cli zone delete -f example.com.
      - name: Delete absent zone
        run: powerdns-cli zone delete -f example.com
      - name: Rectify Zone
        run: powerdns-cli zone rectify example.org
      - name: Notify Zone
        run: powerdns-cli zone notify example.org
# Record Management Tests
      - name: Add Record
        run: powerdns-cli record add add example.org A 10.0.0.1
      - name: Add duplicate record
        run: powerdns-cli record add add example.org A 10.0.0.2
      - name: Add CNAME record with different ttl
        run: powerdns-cli record add --ttl 60 cname example.org CNAME "example.org."
      - name: Run extend on no preexisting record
        run: powerdns-cli record extend extend example.org A 10.0.0.1
      - name: Extend existing record
        run: powerdns-cli record extend extend example.org A 10.0.0.2
      - name: Create a record to delete
        run: powerdns-cli record add delete example.org A 10.0.0.1
      - name: Extend a record to delete
        run: powerdns-cli record extend delete example.org A 10.0.0.2
      - name: Delete part of a record
        run: powerdns-cli record delete delete example.org A 10.0.0.2
      - name: Delete full record
        run: powerdns-cli record delete -a delete example.org A 192.168.0.1
      - name: Create a record to disable
        run: powerdns-cli record add disable example.org A 10.0.0.1
      - name: Disable record
        run: powerdns-cli record disable disable example.org A 10.0.0.1
      - name: Export zone as json
        run: powerdns-cli zone export example.org
      - name: Export zone as bind / axfr
        run: powerdns-cli zone export -b example.org
      - name: Search
        run: powerdns-cli zone search --max 5 "test.example.org"
      - name: Flush zone cache
        run: powerdns-cli zone flush-cache example.org.
# Config Tests
      - name: Show stats
        run: powerdns-cli config stats
      - name: List servers
        run: powerdns-cli config list
      - name: Export server
        run: powerdns-cli config export
# TSIGKey Tests
      - name: Add TSIGKey with defaults
        run: powerdns-cli tsigkey add test1 hmac-md5
      - name: Add TSIGKey with secrets
        run: powerdns-cli tsigkey add test2 hmac-sha1 -s "kp4/24gyYsEzbuTVJRUMoqGFmN3LYgVDzJ/3oRSP7ys="
      - name: List TSIGKeys
        run: powerdns-cli tsigkey list
      - name: Delete TSIGKeys
        run: powerdns-cli tsigkey delete test2
      - name: Update TSIGKey secret
        run: powerdns-cli tsigkey update test1 -s "kp4/24gyYsEzbuTVJRUMoqGFmN3LYgVDzJ/3oRSP7ys="
      - name: Update TSIGKey name
        run: powerdns-cli tsigkey update test1 -n "newname"
      - name: Update TSIGKey algorithm
        run: powerdns-cli tsigkey update newname -a "hmac-sha512"
      - name: Export TSIGKey key
        run: powerdns-cli tsigkey export newname
# Zonemetadata Tests
      - name: Lists metadata
        run: powerdns-cli metadata list example.org
      - name: Add metadata
        run: powerdns-cli metadata add example.org ALSO-NOTIFY 192.0.2.1:5305
      - name: Add duplicate metadata
        run: powerdns-cli metadata add example.org ALSO-NOTIFY 192.0.2.1:5305
      - name: Extend metadata
        run: powerdns-cli metadata extend example.org ALSO-NOTIFY 192.0.2.2:5305
      - name: List single metadata value
        run: powerdns-cli metadata list -l "ALSO-NOTIFY" example.org
      - name: Replace metadata
        run: powerdns-cli metadata update example.org ALSO-NOTIFY 192.0.2.2:5305
      - name: Delete metadata
        run: powerdns-cli metadata delete example.org ALSO-NOTIFY
# Autoprimary Tests
      - name: Add autoprimary
        run: powerdns-cli autoprimary add 127.0.0.1 example.org
      - name: Add autoprimary with name
        run: powerdns-cli autoprimary add -a test123 127.0.0.1 example.com
      - name: List autoprimaries
        run: powerdns-cli autoprimary list
      - name: Delete autoprimary
        run: powerdns-cli autoprimary delete 127.0.0.1 example.org
# Cryptokey Tests
      - name: Add ZSK cryptokey
        run: powerdns-cli cryptokey add --algorithm ecdsap256sha256 --bits 256 example.org zsk
      - name: Add ksk cryptokey
        run: powerdns-cli cryptokey add example.org ksk
      - name: Import a cryptokey secret
        run: >
          powerdns-cli 
          cryptokey add 
          example.org 
          -s 'Private-key-format: v1.2\nAlgorithm: 13 (ECDSAP256SHA256)\nPrivateKey: 1nM02+BeuUuppbSgtDBIV3106HMTdLNMqV7rnb4t0iA=\n' ksk
      - name: List cryptokeys
        run: powerdns-cli cryptokey list example.org
      - name: Delete a cryptokey
        run: powerdns-cli cryptokey delete example.org 1
      - name: Export a cryptokey
        run: powerdns-cli cryptokey export example.org 2
      - name: Enable cryptokey
        run: powerdns-cli cryptokey enable example.org 2
      - name: Disable cryptokey
        run: powerdns-cli cryptokey disable example.org 2
