name: Lint
on:
  pull_request:
  push:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-python@v6
      with:
        python-version: |
            3.10
            3.11
            3.12
            3.13
            3.14
        cache: pip
    - run: pip install .[dev]
    - run: tox run -e lint
