name: Lint project
on:
  pull_request:
  push:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.13.2
        cache: pip
    - run: pip install .[dev]
    - uses: pre-commit/action@v3.0.1
