name: Lint
on:
  pull_request:
  push:
    branches:
    - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-python@v6
      with:
        cache: pip
    - run: pip install .[dev]
    - run: tox run -e lint
