name: Lint project
on:
  pull_request:
  push:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.10.16
        cache: pip
    - run: pip install pylint
    - uses: pre-commit/action@v3.0.1
