name: Unit Tests
on:
  pull_request:
  push:
    tags-ignore: # tags are tested in release.yml
      - "**"
    branches:
      - "**"
  workflow_call:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-python@v6
    - run: pip install .[dev]
    - run: tox run
